apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xAOD-collector
spec:
  schedule: "31 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics-svc-container
            image: atlasanalyticsservice/containers:latest
            command: ["/run.sh"]
            args: ["/xAOD/run.sh"]
            volumeMounts:
            - name: keytab-volume
              mountPath: "/tmp/keytab"
              readOnly: true
          volumes:
          - name: keytab-volume
            secret:
              secretName: analytcssvc-keytab
          restartPolicy: Never
