apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddm-accounting
spec:
  schedule: "20 6 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics-svc-container
            image: atlasanalyticsservice/containers:latest
            command: ["/run.sh"]
            args: ["/DDM/run.sh"]
            volumeMounts:
            - name: keytab-volume
              mountPath: "/tmp/keytab"
              readOnly: true
          volumes:
          - name: keytab-volume
            secret:
              secretName: analytcssvc-keytab
          restartPolicy: Never
