apiVersion: v1
kind: Pod
metadata:
  name: base-pod
spec:
  containers:
  - name: analytics-svc-container
    image: atlasanalyticsservice/containers:latest
    command: ["sleep"]
    args: ["36500000"]
    env:
      - name: MQ_USER
        valueFrom:
          secretKeyRef:
            name: mq-auth
            key: mq_user
      - name: MQ_PASS
        valueFrom:
          secretKeyRef:
            name: mq-auth
            key: mq_pass
    volumeMounts:
    - name: mq-volume
      mountPath: "/tmp/mq"
      readOnly: true
    - name: keytab-volume
      mountPath: "/tmp/keytab"
      readOnly: true
  volumes:
  - name: mq-volume
    secret:
      secretName: mq-secret
  - name: keytab-volume
    secret:
      secretName: analytcssvc-keytab
  restartPolicy: Never