apiVersion: v1
kind: Pod
metadata:
  name: fts-pod
spec:
  containers:
  - name: analytics-svc-container
    image: atlasanalyticsservice/containers:latest
    args: ["/FTS/run.sh"]
    env:
      - name: MQ_USER
        valueFrom:
          secretKeyRef:
            name: mq-auth
            key: mq_user
      - name: MQ_PASS
        valueFrom:
          secretKeyRef:
            name: mq-auth
            key: mq_pass
      - name: MQ_HOST
        valueFrom:
          secretKeyRef:
            name: mq-auth
            key: mq_host
  restartPolicy: Never