apiVersion: v1
kind: Pod
metadata:
  name: fts-pod
  namespace: aaas
spec:
  containers:
  - name: analytics-svc-container
    image: atlasanalyticsservice/containers:latest
    command: ["/run.sh"]
    args: ["/FTS/run.sh"]
    env:
      - name: MQ_USER
        valueFrom:
          secretKeyRef:
            name: mq-auth-fts
            key: mq_user
      - name: MQ_PASS
        valueFrom:
          secretKeyRef:
            name: mq-auth-fts
            key: mq_pass
      - name: MQ_HOST
        valueFrom:
          secretKeyRef:
            name: mq-auth-fts
            key: mq_host
      - name: ES_USER
        valueFrom:
          secretKeyRef:
            name: es-auth-fts
            key: es_user
      - name: ES_PASS
        valueFrom:
          secretKeyRef:
            name: es-auth-fts
            key: es_pass
      - name: ES_HOST
        valueFrom:
          secretKeyRef:
            name: es-auth-fts
            key: es_host
  restartPolicy: Never