apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boinc-cms-dev-collector
spec:
  schedule: "43 */1 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics-svc-container
            image: atlasanalyticsservice/containers:latest
            command: ["/run.sh"]
            args: ["/BOINC/run-cms-dev.sh"]
            env:
            - name: BOINC_USER
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_cms_dev_user
            - name: BOINC_PASS
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_cms_dev_pass
            - name: BOINC_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_cms_dev_connection_string
            volumeMounts:
            - name: keytab-volume
              mountPath: "/tmp/keytab"
              readOnly: true
          volumes:
          - name: keytab-volume
            secret:
              secretName: analytcssvc-keytab
          restartPolicy: Never
