apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boinc-dev-collector
spec:
  schedule: "33 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics-svc-container
            image: atlasanalyticsservice/containers:latest
            command: ["/run.sh"]
            args: ["/BOINC/run-dev.sh"]
            env:
            - name: BOINC_DEV_USER
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_dev_user
            - name: BOINC_DEV_PASS
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_dev_pass
            - name: BOINC_DEV_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: boinc-secret
                  key: boinc_dev_connection_string
            volumeMounts:
            - name: keytab-volume
              mountPath: "/tmp/keytab"
              readOnly: true
          volumes:
          - name: keytab-volume
            secret:
              secretName: analytcssvc-keytab
          restartPolicy: Never
